### ISSUE TITLE
react-server-cli should run help without local react-server

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#193]
The help is what you would want to read to find out that you need a locally-installed `react-server`.

```
dougwade packages/generator-react-server ‹dont-run-bower*› » react-server-cli --help                                                                                          1 ↵
module.js:327
    throw err;
    ^

Error: Cannot find module 'react-server'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-server-cli/target/startServer.js:15:20)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/react-server-cli/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
dougwade packages/generator-react-server ‹dont-run-bower*› » react-server-cli -?                                                                                              1 ↵
zsh: no matches found: -?
dougwade packages/generator-react-server ‹dont-run-bower*› » react-server-cli -\?                                                                                             1 ↵
module.js:327
    throw err;
    ^

Error: Cannot find module 'react-server'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-server-cli/target/startServer.js:15:20)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/react-server-cli/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by gigabo** [comment]
Yes!

**Comment by doug-wade** [comment]
I think this was fixed in https://github.com/redfin/react-server/pull/484

```
dougwade ~ » react-server --help
Usage: react-server <command> [options]

Commands:
  start     Start the server
  compile   Compile static assets
  init      Initialize a React Server site
  add-page  Add a page to an existing site

Options:
  --routes-file        The routes file to load. Default is 'routes.js'.
  -p, --port           Port to start listening for react-server. Default is 3000
                       .
  --host               Hostname to start listening for react-server     [string]
  --js-port            Port to start listening for react-server's JavaScript.
                       Default is 3001.
  --https              If true, the server will start up using https with a self
                       -signed certificate. Note that browsers do not trust self
                       -signed certificates by default, so you will have to
                       click through some warning screens. This is a quick and
                       dirty way to test HTTPS, but it has some limitations and
                       should never be used in production. Requires OpenSSL to
                       be installed. Default is false.                 [boolean]
  --https-key          Start the server using HTTPS with this private key file
                       in PEM format. Requires https-cert to be set as well.
                       Default is none.                                 [string]
  --https-cert         Start the server using HTTPS with this cert file in PEM
                       format. Requires https-key to be set as well. Default is
                       none.                                            [string]
  --https-ca           Start the server using HTTPS with this certificate
                       authority file in PEM format. Also requires https-key and
                       https-cert to start the server. Default is none.
                                                                        [string]
  --https-pfx          Start the server using HTTPS with this file containing
                       the private key, certificate and CA certs of the server
                       in PFX or PKCS12 format. Mutually exclusive with https-
                       key, https-cert, and https-ca. Default is none.  [string]
  --https-passphrase   A passphrase for the private key or pfx. Requires https-
                       key or https-pfx to be set. Default is none.     [string]
  -h, --hot            Load the app so that it can be hot reloaded in the
                       browser. Default is false in production mode, true
                       otherwise.                                      [boolean]
  -m, --minify         Optimize client JS when option is present. Takes a bit
                       longer to compile. Default is true in production mode,
                       false otherwise.                                [boolean]
  --long-term-caching  Use long-term cache headers for the static JS & CSS files
                       . Default is true in production mode, false otherwise.
                                                                       [boolean]
  --log-level          Set the severity level for the logs being reported.
                       Values are, in ascending order of severity: 'debug', '
                       info', 'notice', 'warning', 'error', 'critical', 'alert
                       ', 'emergency'. Default is 'notice' in production mode, '
                       debug' otherwise.                                [string]
  --timing-log-level   Set the severity level for the timing logs. Values are,
                       in ascending order of verbosity: 'none', 'slow', 'fine
                       ', 'fast. Default is 'none' in production mode, 'fast'
                       otherwise.                                       [string]
  --gauge-log-level    Set the severity level for the gauge logs. Values are, in
                       ascending order of severity: 'no', 'hi', 'lo', 'ok'.
                       Default is 'no' in production mode, 'ok' otherwise.
                                                                        [string]
  --compile-only       Compile the client JavaScript only, and don't start any
                       servers. This is what you want to do if you are building
                       the client JavaScript to be hosted on a CDN. Unless you
                       have a very specific reason, it's almost alway a good
                       idea to only do this in production mode. Defaults to
                       false.                                          [boolean]
  --js-url             A URL base for the pre-compiled client JavaScript.
                       Setting a value for jsurl means that react-server-cli
                       will not compile the client JavaScript at all, and it
                       will not serve up any JavaScript. Obviously, this means
                       that --jsurl overrides all of the options related to
                       JavaScript compilation: --hot, --minify, and --
                       bundleperroute.                                  [string]
  --stats              Output webpack stats to __clientTemp/build/stats.json.
                       Recommended for use with webpack-bundle-size-analyzer.
                                                      [boolean] [default: false]
  -?, --help           Show help                                       [boolean]
```

**Comment by gigabo** [comment]
Indeed.  Thanks @doug-wade.
