### ISSUE TITLE
react-server-gulp-module-tagger throws module not found error

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#210]
```
dougwade npm-experiments/rsgmt » npm i react-server-gulp-module-tagger@\^0.2.5
react-server-gulp-module-tagger@0.2.7 node_modules/react-server-gulp-module-tagger
├── gulp-replace@0.5.2 (replacestream@2.0.0, istextorbinary@1.0.2, event-stream@3.2.1)
└── gulp-foreach@0.1.0 (through2@0.6.5, gulp-util@2.2.20)
dougwade npm-experiments/rsgmt » ls node_modules/react-server-gulp-module-tagger
node_modules  package.json
```
there should be an `index.js` in `react-server-gulp-module-tagger`, but there is not because [npm is using `.gititgnore` to ignore files for publishing](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)

**Comment by doug-wade** [comment]
see https://travis-ci.org/redfin/react-server/builds/132703974

```
Error: Command failed: npm install lodash@^4.8.2 q@^1.4.1 react@~0.14.2 react-dom@~0.14.2 react-server@../react-server react-server-cli@../react-server-cli rimraf@^2.5.2 superagent@1.2.0
(node:3788) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! addLocal Could not install /home/travis/build/redfin/react-server/packages/react-server
(node:3871) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.0/bin/node" "/home/travis/.nvm/versions/node/v6.2.0/bin/npm" "install" "lodash@^4.8.2" "q@^1.4.1" "react@~0.14.2" "react-dom@~0.14.2" "react-server@../react-server" "react-server-cli@../react-server-cli" "rimraf@^2.5.2" "superagent@1.2.0"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-server@0.2.12 prepublish: `npm run clean; gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-server@0.2.12 prepublish script 'npm run clean; gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean; gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-server
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/redfin/react-server/packages/react-server-integration-tests/npm-debug.log
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.0/bin/node" "/home/travis/.nvm/versions/node/v6.2.0/bin/npm" "run" "bootstrap"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! @ bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ bootstrap script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/redfin/react-server/npm-debug.log
The command "npm run bootstrap" failed and exited with 1 during .
```

**Comment by doug-wade** [comment]
This only applies to 0.2.7; use 0.2.6 instead
