### ISSUE TITLE
Build storminess on master

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#216]
Merging #150 seems to have made the build fail inconsistently and unexpectedly

**Comment by doug-wade** [comment]
https://travis-ci.org/redfin/react-server/builds/132744187
```
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-server@0.2.12 prepublish: `npm run clean; gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-server@0.2.12 prepublish script 'npm run clean; gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean; gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-server
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/redfin/react-server/packages/react-server-integration-tests/npm-debug.log
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.0/bin/node" "/home/travis/.nvm/versions/node/v6.2.0/bin/npm" "run" "bootstrap"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! @ bootstrap: `npm i; lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ bootstrap script 'npm i; lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i; lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/redfin/react-server/npm-debug.log
The command "npm run bootstrap" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by doug-wade** [comment]
https://travis-ci.org/redfin/react-server/builds/132732945
```
Errored while running npm script 'test' in 'react-server-cli'
Error: Command failed: npm run test 
(node:4128) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.0/bin/node" "/home/travis/.nvm/versions/node/v6.2.0/bin/npm" "run" "test"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-server-cli@0.2.12 test: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-server-cli@0.2.12 test script 'gulp test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-server-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-server-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-server-cli
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/redfin/react-server/packages/react-server-cli/npm-debug.log
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
Errored while running RunCommand.execute
Error: Command failed: npm run test 
(node:4128) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.0/bin/node" "/home/travis/.nvm/versions/node/v6.2.0/bin/npm" "run" "test"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-server-cli@0.2.12 test: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-server-cli@0.2.12 test script 'gulp test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-server-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-server-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-server-cli
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/redfin/react-server/packages/react-server-cli/npm-debug.log
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by gigabo** [comment]
@doug-wade - `lerna bootstrap` runs multiple installs concurrently.  Maybe the `clean` during one is clobbering the build for another?  We might not be able to run `clean` during prepublish.  Maybe we could add it instead as _lerna_ prepublish script?

**Comment by doug-wade** [comment]
@gigabo I can't find anything in the [lerna docs](https://github.com/lerna/lerna/tree/v2.0.0-beta.13#publishing) or [site](https://lernajs.io/) about a _lerna_ prepublish; do I just add a `scripts` hash to `lerna.json`?

**Comment by gigabo** [comment]
@doug-wade - Looks like it requires a [`scripts/prepublish.js`](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L306) to live in each package.

Short term let's at least just get the clean out of our npm prepublish to get builds passing.  Just _having the option_ to clean before publishing is a good step forward. :)
