### ISSUE TITLE
`npm test` is broken on master

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#265]
```
dougwade code/react-server ‹start-server-tests*› » git co master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)
dougwade code/react-server ‹master*› » git pull upstream master
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 19 (delta 7), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.
From https://github.com/redfin/react-server
 * branch            master     -> FETCH_HEAD
   f0d9ad6..ee23e0e  master     -> upstream/master
Updating f0d9ad6..ee23e0e
Fast-forward
 packages/react-server/README.md                                               | 10 +++++++---
 packages/react-server/core/ReactServerAgent/Cache.js                          |  7 ++++++-
 packages/react-server/core/ReactServerAgent/__tests__/ReactServerAgentSpec.js | 37 +++++++++++++++++++++++++++++++++++++
 3 files changed, 50 insertions(+), 4 deletions(-)
dougwade code/react-server ‹master*› » npm test

> @ test /Users/doug.wade/code/react-server
> lerna run test

Lerna v2.0.0-beta.14

> babel-preset-react-server@0.3.0 test /Users/doug.wade/code/react-server/packages/babel-preset-react-server
> echo "All good!"

All good!


> react-server-data-bundle-cache@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server-data-bundle-cache
> gulp test

[12:33:52] Using gulpfile ~/code/react-server/packages/react-server-data-bundle-cache/gulpfile.js
[12:33:52] Starting 'nsp'...
[12:33:52] Starting 'eslint'...
[12:33:53] Finished 'eslint' after 865 ms
[12:33:53] (+) No known vulnerabilities found
[12:33:53] Finished 'nsp' after 919 ms
[12:33:53] Starting 'test'...
[12:33:53] Finished 'test' after 7.17 μs


> react-server-cli@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server-cli
> gulp test

[12:33:51] Requiring external module babel-register
[12:33:58] Using gulpfile ~/code/react-server/packages/react-server-cli/gulpfile.babel.js
[12:33:58] Starting 'eslint'...
[12:33:59] Finished 'eslint' after 1.04 s
[12:33:59] Starting 'test'...
[12:33:59] Finished 'test' after 24 μs


> react-server-examples@ test /Users/doug.wade/code/react-server/packages/react-server-examples
> gulp test

[12:33:54] Requiring external module babel-register
[12:33:59] Using gulpfile ~/code/react-server/packages/react-server-examples/gulpfile.babel.js
[12:33:59] Starting 'eslint'...
[12:33:59] Finished 'eslint' after 508 ms
[12:33:59] Starting 'test'...
[12:33:59] Finished 'test' after 27 μs


> react-server-gulp-module-tagger@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server-gulp-module-tagger
> gulp test

[12:34:01] Using gulpfile ~/code/react-server/packages/react-server-gulp-module-tagger/gulpfile.js
[12:34:01] Starting 'nsp'...
[12:34:01] Starting 'eslint'...
[12:34:02] Finished 'eslint' after 540 ms
[12:34:02] (+) No known vulnerabilities found
[12:34:02] Finished 'nsp' after 863 ms
[12:34:02] Starting 'test'...
[12:34:02] Finished 'test' after 8.1 μs


> react-server@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server
> gulp test

[12:33:52] Using gulpfile ~/code/react-server/packages/react-server/gulpfile.js
[12:33:52] Starting 'compileServer'...
[12:33:53] Starting 'compileClient'...
[12:33:53] Starting 'eslint'...
[12:33:53] Starting 'nsp'...
[12:33:53] (+) No known vulnerabilities found
[12:33:53] Finished 'nsp' after 895 ms
[12:34:02] Finished 'eslint' after 9.83 s
[12:34:03] Finished 'compileServer' after 11 s
[12:34:03] Finished 'compileClient' after 11 s
[12:34:03] Starting 'jasmine'...
..........................CacheEntry {
  cache: RequestDataCache { dataCache: { '/error': [Object] } },
  cacheWhitelist: undefined,
  requesters: 1,
  dfd:
   defer {
     promise: { state: 'rejected', reason: [Object] },
     resolve: [Function],
     fulfill: [Function],
     reject: [Function],
     notify: [Function] },
  loaded: true,
  res: undefined,
  err:
   { original: null,
     response:
      { body: [Object],
        text: '{"error":"An Error Occurred"}',
        type: 'application/json',
        status: 503,
        statusType: 5,
        info: false,
        ok: false,
        clientError: false,
        serverError: true,
        error: [Object],
        accepted: false,
        noContent: false,
        badRequest: false,
        unauthorized: false,
        notAcceptable: false,
        notFound: false,
        forbidden: false },
     status: 503 },
  url: '/error',
  requestData:
   { urlPath: '/error',
     method: 'GET',
     queryParams: [],
     postParams: {},
     type: 'json' } }
........

34 specs, 0 failures
Finished in 0 seconds
[12:34:05] Finished 'jasmine' after 1.74 s
[12:34:05] Starting 'test'...
[12:34:05] Finished 'test' after 8.53 μs

Errored while running npm script 'test' in 'react-server-integration-tests'
Error: Command failed: /bin/sh -c npm run test
Failed to start server TypeError: Path must be a string. Received { routesFile: '/Users/doug.wade/code/react-server/packages/react-server-integration-tests/test-temp/routes_169660b36bb5e37beed40219509786e8.js',
  hot: false,
  port: 8770,
  logLevel: 'emergency',
  timingLogLevel: 'none',
  gaugeLogLevel: 'no' }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at startImpl (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:101:34)
    at exports.default (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:83:9)
    at startServer (testHelper.js:93:9)
    at Object.<anonymous> (testHelper.js:270:23)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at Object.fn (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2345:13)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at TreeProcessor.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2209:7)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-server-integration-tests@ test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-server-integration-tests@ test script 'gulp test'.
npm ERR! This is most likely a problem with the react-server-integration-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-server-integration-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/react-server/packages/react-server-integration-tests/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Errored while running RunCommand.execute
Error: Command failed: /bin/sh -c npm run test
Failed to start server TypeError: Path must be a string. Received { routesFile: '/Users/doug.wade/code/react-server/packages/react-server-integration-tests/test-temp/routes_169660b36bb5e37beed40219509786e8.js',
  hot: false,
  port: 8770,
  logLevel: 'emergency',
  timingLogLevel: 'none',
  gaugeLogLevel: 'no' }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at startImpl (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:101:34)
    at exports.default (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:83:9)
    at startServer (testHelper.js:93:9)
    at Object.<anonymous> (testHelper.js:270:23)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at Object.fn (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2345:13)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at TreeProcessor.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2209:7)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-server-integration-tests@ test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-server-integration-tests@ test script 'gulp test'.
npm ERR! This is most likely a problem with the react-server-integration-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-server-integration-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/react-server/packages/react-server-integration-tests/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm ERR! Test failed.  See above for more details.
dougwade code/react-server ‹master*› » npm test                                                                                                                               1 ↵

> @ test /Users/doug.wade/code/react-server
> lerna run test

Lerna v2.0.0-beta.14

> babel-preset-react-server@0.3.0 test /Users/doug.wade/code/react-server/packages/babel-preset-react-server
> echo "All good!"

All good!


> react-server-data-bundle-cache@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server-data-bundle-cache
> gulp test

[12:34:47] Using gulpfile ~/code/react-server/packages/react-server-data-bundle-cache/gulpfile.js
[12:34:47] Starting 'nsp'...
[12:34:47] Starting 'eslint'...
[12:34:48] (+) No known vulnerabilities found
[12:34:48] Finished 'nsp' after 830 ms
[12:34:48] Finished 'eslint' after 872 ms
[12:34:48] Starting 'test'...
[12:34:48] Finished 'test' after 7.37 μs


> react-server@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server
> gulp test

[12:34:47] Using gulpfile ~/code/react-server/packages/react-server/gulpfile.js
[12:34:47] Starting 'compileServer'...
[12:34:47] Starting 'compileClient'...
[12:34:48] Starting 'eslint'...
[12:34:48] Starting 'nsp'...
[12:34:49] (+) No known vulnerabilities found
[12:34:49] Finished 'nsp' after 1.08 s
[12:34:50] Finished 'eslint' after 2.48 s
[12:34:50] Finished 'compileClient' after 2.5 s
[12:34:50] Finished 'compileServer' after 2.53 s
[12:34:50] Starting 'jasmine'...
..........................CacheEntry {
  cache: RequestDataCache { dataCache: { '/error': [Object] } },
  cacheWhitelist: undefined,
  requesters: 1,
  dfd:
   defer {
     promise: { state: 'rejected', reason: [Object] },
     resolve: [Function],
     fulfill: [Function],
     reject: [Function],
     notify: [Function] },
  loaded: true,
  res: undefined,
  err:
   { original: null,
     response:
      { body: [Object],
        text: '{"error":"An Error Occurred"}',
        type: 'application/json',
        status: 503,
        statusType: 5,
        info: false,
        ok: false,
        clientError: false,
        serverError: true,
        error: [Object],
        accepted: false,
        noContent: false,
        badRequest: false,
        unauthorized: false,
        notAcceptable: false,
        notFound: false,
        forbidden: false },
     status: 503 },
  url: '/error',
  requestData:
   { urlPath: '/error',
     method: 'GET',
     queryParams: [],
     postParams: {},
     type: 'json' } }
........

34 specs, 0 failures
Finished in 0 seconds
[12:34:51] Finished 'jasmine' after 1.45 s
[12:34:51] Starting 'test'...
[12:34:51] Finished 'test' after 7.03 μs


> react-server-gulp-module-tagger@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server-gulp-module-tagger
> gulp test

[12:34:53] Using gulpfile ~/code/react-server/packages/react-server-gulp-module-tagger/gulpfile.js
[12:34:53] Starting 'nsp'...
[12:34:53] Starting 'eslint'...
[12:34:53] Finished 'eslint' after 395 ms
[12:34:54] (+) No known vulnerabilities found
[12:34:54] Finished 'nsp' after 700 ms
[12:34:54] Starting 'test'...
[12:34:54] Finished 'test' after 7.18 μs


> react-server-cli@0.3.0 test /Users/doug.wade/code/react-server/packages/react-server-cli
> gulp test

[12:34:46] Requiring external module babel-register
[12:34:53] Using gulpfile ~/code/react-server/packages/react-server-cli/gulpfile.babel.js
[12:34:53] Starting 'eslint'...
[12:34:54] Finished 'eslint' after 981 ms
[12:34:54] Starting 'test'...
[12:34:54] Finished 'test' after 14 μs


> react-server-examples@ test /Users/doug.wade/code/react-server/packages/react-server-examples
> gulp test

[12:34:50] Requiring external module babel-register
[12:34:54] Using gulpfile ~/code/react-server/packages/react-server-examples/gulpfile.babel.js
[12:34:54] Starting 'eslint'...
[12:34:54] Finished 'eslint' after 474 ms
[12:34:54] Starting 'test'...
[12:34:54] Finished 'test' after 13 μs


> react-server-test-pages@0.0.0 test /Users/doug.wade/code/react-server/packages/react-server-test-pages
> gulp test

[12:34:56] Requiring external module babel-register
[12:35:01] Using gulpfile ~/code/react-server/packages/react-server-test-pages/gulpfile.babel.js
[12:35:02] Starting 'eslint'...
[12:35:06] Finished 'eslint' after 4.01 s
[12:35:06] Starting 'test'...
[12:35:06] Finished 'test' after 23 μs

Errored while running npm script 'test' in 'react-server-integration-tests'
Error: Command failed: /bin/sh -c npm run test
Failed to start server TypeError: Path must be a string. Received { routesFile: '/Users/doug.wade/code/react-server/packages/react-server-integration-tests/test-temp/routes_169660b36bb5e37beed40219509786e8.js',
  hot: false,
  port: 8770,
  logLevel: 'emergency',
  timingLogLevel: 'none',
  gaugeLogLevel: 'no' }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at startImpl (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:101:34)
    at exports.default (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:83:9)
    at startServer (testHelper.js:93:9)
    at Object.<anonymous> (testHelper.js:270:23)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at Object.fn (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2345:13)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at TreeProcessor.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2209:7)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-server-integration-tests@ test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-server-integration-tests@ test script 'gulp test'.
npm ERR! This is most likely a problem with the react-server-integration-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-server-integration-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/react-server/packages/react-server-integration-tests/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Errored while running RunCommand.execute
Error: Command failed: /bin/sh -c npm run test
Failed to start server TypeError: Path must be a string. Received { routesFile: '/Users/doug.wade/code/react-server/packages/react-server-integration-tests/test-temp/routes_169660b36bb5e37beed40219509786e8.js',
  hot: false,
  port: 8770,
  logLevel: 'emergency',
  timingLogLevel: 'none',
  gaugeLogLevel: 'no' }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at startImpl (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:101:34)
    at exports.default (/Users/doug.wade/code/react-server/packages/react-server-integration-tests/node_modules/react-server-cli/target/startServer.js:83:9)
    at startServer (testHelper.js:93:9)
    at Object.<anonymous> (testHelper.js:270:23)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at Object.fn (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2345:13)
    at attemptAsync (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
    at QueueRunner.run (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
    at QueueRunner.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
    at Env.queueRunnerFactory (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
    at TreeProcessor.execute (/Users/doug.wade/code/react-server/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2209:7)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-server-integration-tests@ test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-server-integration-tests@ test script 'gulp test'.
npm ERR! This is most likely a problem with the react-server-integration-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-server-integration-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/react-server/packages/react-server-integration-tests/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm ERR! Test failed.  See above for more details.
```

**Comment by doug-wade** [comment]
maybe related to these warnings?
```
dougwade code/react-server ‹master*› » lerna bootstrap
Lerna v2.0.0-beta.14
Linking all dependencies
Version mismatch inside "react-server-integration-tests". Depends on "react-server@0.3.0" instead of "react-server@../react-server".
Version mismatch inside "react-server-integration-tests". Depends on "react-server-cli@0.3.0" instead of "react-server-cli@../react-server-cli".
Version mismatch inside "react-server-test-pages". Depends on "react-server@0.3.0" instead of "react-server@../react-server".
Version mismatch inside "react-server-test-pages". Depends on "react-server-cli@0.3.0" instead of "react-server-cli@../react-server-cli".
Version mismatch inside "react-server-test-pages". Depends on "react-server-data-bundle-cache@0.3.0" instead of "react-server-data-bundle-cache@../react-server-data-bundle-cache".
Successfully bootstrapped 9 packages.
```

**Comment by doug-wade** [comment]
This was resolved with an `npm run nuke && npm run bootstrap`
