### ISSUE TITLE
Error during generator with node 6.3.1

### ISSUE THREAD

**Issue by mcianc** [redfin/react-server#577]
E:\Work\Test2> yo react-server

     _-----_     ╭──────────────────────────╮
    |       |    │  Welcome to the shining  │
    |--(o)--|    │  generator-react-server  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What would you like to call your app? (Test2)

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (E:\Users\Marco\AppData\Roaming\npm\node_modules\generator-react-server\node_modules\yeoman-generator\lib\base.js:232:45)
    at module.exports.yeoman.Base.extend.prompting (E:\Users\Marco\AppData\Roaming\npm\node_modules\generator-react-server\generators\app\index.js:35:15)
    at Object.<anonymous> (E:\Users\Marco\AppData\Roaming\npm\node_modules\generator-react-server\node_modules\yeoman-generator\lib\base.js:431:23)
    at E:\Users\Marco\AppData\Roaming\npm\node_modules\generator-react-server\node_modules\run-async\index.js:26:25
    at E:\Users\Marco\AppData\Roaming\npm\node_modules\generator-react-server\node_modules\run-async\index.js:25:19
    at E:\Users\Marco\AppData\Roaming\npm\node_modules\generator-react-server\node_modules\yeoman-generator\lib\base.js:432:9
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
 PS E:\Work\Test2> node -v
v6.3.1

Any Idea? I tried to unistall and reinstall yoeman and generator

**Comment by doug-wade** [comment]
@mcianc what version of yeoman are you running (`yo -v`)?  [Stackoverflow](http://stackoverflow.com/questions/37193740/error-unhandled-error-event-after-running-yo-generator) seems to think that this can be solved by upgrading to the latest version of yo (`npm update -g yo`)

**Comment by mcianc** [comment]
my yoeman is v 1.7.0

**Comment by doug-wade** [comment]
Hooray :tada:
