### ISSUE TITLE
yo react-server returns the following error : TypeError: Cannot read property 'then' of undefined     at Base.prompt (/usr/lib/node_modules/generator-react-server/node_modules/yeoman-generator/lib/base.js:232:44)

### ISSUE THREAD

**Issue by jay3dec** [redfin/react-server#670]
Runnig `yo react-server `returns the following error : 

> [?] What would you like to call your app? (RS) events.js:141
      throw er; // Unhandled 'error' event
      ^

 

>  TypeError: Cannot read property 'then' of undefined
>     at Base.prompt (/usr/lib/node_modules/generator-react-server/node_modules/yeoman-generator/lib/base.js:232:44)
>     at module.exports.yeoman.Base.extend.prompting (/usr/lib/node_modules/generator-react-server/generators/app/index.js:35:15)
>     at Object.<anonymous> (/usr/lib/node_modules/generator-react-server/node_modules/yeoman-generator/lib/base.js:431:23)
>     at /usr/lib/node_modules/generator-react-server/node_modules/run-async/index.js:26:25
>     at /usr/lib/node_modules/generator-react-server/node_modules/run-async/index.js:25:19
>     at /usr/lib/node_modules/generator-react-server/node_modules/yeoman-generator/lib/base.js:432:9
>     at processImmediate [as _immediateCallback] (timers.js:383:17)
>

**Comment by jay3dec** [comment]
Ok, it seemed like my yo was old version and once updated it all ran fine. the following link helped

http://codehandbook.org/typeerror-cannot-read-property-then-of-undefined-yo-react-server/
