### ISSUE TITLE
CSS loading from node_module isn't working : Module parse failed, you may need another loader

### ISSUE THREAD

**Issue by mtrabelsi** [redfin/react-server#878]
How to **NOT** reproduce : 

1) install react-server and create simple project
2) create a simple css in your project and include it like the follow : 

`import './mycss.css'`

 3) everything is correct, see next 

How to reproduce :
1) install react-server and create simple project
2) install this Player component that I've published : 
`  npm install react-player-js --save`

and in /pages/yourPage.js try to include the player : 
`import Player from 'react-player-js'`
These errors will be thrown : 

```
> radio@0.0.1 start /home/marwen/Documents/radio
> react-server start

2017-02-11T22:00:09.610Z - warning: [react-server-cli.src.logProductionWarnings] PRODUCTION WARNING: the following current settings are discouraged in production environments. (If you are developing, carry on!):
2017-02-11T22:00:09.613Z - warning: [react-server-cli.src.logProductionWarnings] -- Minification is disabled. To enable, set minify to true (--minify at the command-line) or set NODE_ENV=production.
2017-02-11T22:00:09.614Z - warning: [react-server-cli.src.logProductionWarnings] -- Long-term caching is disabled. To enable, set longTermCaching to true (--long-term-caching at the command-line) or set NODE_ENV=production to turn on.
2017-02-11T22:00:09.614Z - info: [react-server-cli.src.logProductionWarnings] NODE_ENV is set to undefined
2017-02-11T22:00:09.648Z - notice: [react-server-cli.src.commands.start] Starting servers...
There were errors in the JavaScript compilation.
./~/react-player-js/dist/player.css
Module parse failed: /home/marwen/Documents/radio/node_modules/react-player-js/dist/player.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:727:47)
 @ ./~/react-player-js/dist/index.js 43:0-23
./~/react-player-js/dist/play/play.css
Module parse failed: /home/marwen/Documents/radio/node_modules/react-player-js/dist/play/play.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:727:47)
 @ ./~/react-player-js/dist/play/play.js 31:0-21
./~/react-player-js/dist/volume/volume.css
Module parse failed: /home/marwen/Documents/radio/node_modules/react-player-js/dist/volume/volume.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:727:47)
 @ ./~/react-player-js/dist/volume/volume.js 31:0-23
./~/react-player-js/dist/timer/timer.css
Module parse failed: /home/marwen/Documents/radio/node_modules/react-player-js/dist/timer/timer.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/marwen/Documents/radio/node_modules/acorn/dist/acorn.js:727:47)
 @ ./~/react-player-js/dist/timer/timer.js 31:0-22
2017-02-11T22:00:13.338Z - info: [react-server-cli.src.commands.start] Starting HTML server...
2017-02-11T22:00:13.416Z - error: [react-server-cli.src.commands.start]  message=There were errors in the JavaScript compilation., stack=Error: There were errors in the JavaScript compilation.
    at handleCompilationErrors (/home/marwen/Documents/radio/node_modules/react-server-cli/target/handleCompilationErrors.js:25:10)
    at /home/marwen/Documents/radio/node_modules/react-server-cli/target/commands/start.js:162:55
    at Compiler.<anonymous> (/home/marwen/Documents/radio/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/home/marwen/Documents/radio/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/home/marwen/Documents/radio/node_modules/webpack/lib/Compiler.js:187:11)
    at /home/marwen/Documents/radio/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/home/marwen/Documents/radio/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/home/marwen/Documents/radio/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/home/marwen/Documents/radio/node_modules/webpack/lib/Compiler.js:267:14)
    at /home/marwen/Documents/radio/node_modules/webpack/node_modules/async/lib/async.js:52:16
(node:26912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: There were errors in the JavaScript compilation.
(node:26912) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2017-02-11T22:00:13.423Z - info: [react-server-cli.src.commands.start] Started HTML server over HTTP on host localhost:3000
```

**Comment by mtrabelsi** [comment]
You can also reproduce the same behavior when importing css directly from **node_module**!

**Comment by kafeltz** [comment]
How to fix this? I had to export the file from node_modules and imported manually. Super ugly.

**Comment by kafeltz** [comment]
@mtrabelsi I found the issue.

By default, the CSS loader from react-server has an exclude filter for folder. I have overwritten the config:

```
export default (webpackConfig) => {
     webpackConfig.module.loaders.unshift({
        test: /\.css$/,
        loader: '/Users/ismael/projects/react-server/node_modules/react-server-cli/target/NonCachingExtractTextLoader.js?{remove:true}!css-loader',
        //exclude: /node_modules/   <------------------ this is the problem!
    })

    return webpackConfig
}

```

**Comment by gigabo** [comment]
Oh, interesting.  Can we just remove that?  @jhnns any danger here?

**Comment by jhnns** [comment]
No, even the opposite: I think, the `exclude` option has no real benefits here. Usually, you use the `exclude` `node_modules` option in conjunction with the babel-loader (or any js-loader) to speed up the build. This is because you can expect to get pre-compiled JS via npm. But CSS files need to be processed.

There is no performance benefit here because if you don't process CSS, the build is simply broken 😁

**Comment by gigabo** [comment]
Thanks @jhnns.

@mtrabelsi @kafeltz I think https://github.com/redfin/react-server/pull/892 should do the trick?

**Comment by kafeltz** [comment]
Cool!

**Comment by mtrabelsi** [comment]
I just review the PR, otherwise thanks for your time guys :-)
