### ISSUE TITLE
Unable to start server (incompatibility with Node >= v8?) - TypeError: hasOwnProperty

### ISSUE THREAD

**Issue by joshuamanns** [redfin/react-server#941]
After a fresh `yo react-server`, running `npm start` throws the following error.

```
TypeError: require.cache.hasOwnProperty is not a function
    at /mnt/c/dev/project/project/node_modules/react-server-cli/target/serverSideHotModuleReload.js:37:64
    at Array.map (native)
    at serverSideHotModuleReload (/mnt/c/dev/project/project/node_modules/react-server-cli/target/serverSideHotModuleReload.js:36:37)
    at Compiler.<anonymous> (/mnt/c/dev/project/project/node_modules/react-server-cli/target/compileClient.js:213:45)
    at Compiler.applyPlugins (/mnt/c/dev/project/project/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/mnt/c/dev/project/project/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/mnt/c/dev/project/project/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/mnt/c/dev/project/project/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/mnt/c/dev/project/project/node_modules/webpack/lib/Compiler.js:58:19)
    at /mnt/c/dev/project/project/node_modules/webpack/lib/Compiler.js:275:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
I'm running the latest stable version of Node.

**Comment by dfadev** [comment]
See PR #947
