### ISSUE TITLE
TypeError: require.cache.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by EthanOrange** [redfin/react-server#942]
platform: win10 *64
node: v 8.1.2
npm : v 5.0.4

**Comment by EthanOrange** [comment]
npm run start error

**Comment by rutger** [comment]
+1

**Comment by AlecBoutin** [comment]
Seems to be a problem with Node 8.x. The require.cache object no longer has a hasOwnProperty method. Change is reproducible by openning node REPL and running `require.cache.hasOwnProperty`.

Full stack trace
```C:\Users\Alec\Code\react-server-test\node_modules\react-server-cli\target\serverSideHotModuleReload.js:37
                if (/node_modules/.test(filename) === false && require.cache.hasOwnProperty(filename)) {
                                                                             ^

TypeError: require.cache.hasOwnProperty is not a function
    at C:\Users\Alec\Code\react-server-test\node_modules\react-server-cli\target\serverSideHotModuleReload.js:37:64
    at Array.map (native)
    at serverSideHotModuleReload (C:\Users\Alec\Code\react-server-test\node_modules\react-server-cli\target\serverSideHotModuleReload.js:36:37)
    at Compiler.<anonymous> (C:\Users\Alec\Code\react-server-test\node_modules\react-server-cli\target\compileClient.js:213:45)
    at Compiler.applyPlugins (C:\Users\Alec\Code\react-server-test\node_modules\tapable\lib\Tapable.js:26:37)
    at Watching._done (C:\Users\Alec\Code\react-server-test\node_modules\webpack\lib\Compiler.js:78:17)
    at Watching.<anonymous> (C:\Users\Alec\Code\react-server-test\node_modules\webpack\lib\Compiler.js:61:18)
    at Compiler.emitRecords (C:\Users\Alec\Code\react-server-test\node_modules\webpack\lib\Compiler.js:282:37)
    at Watching.<anonymous> (C:\Users\Alec\Code\react-server-test\node_modules\webpack\lib\Compiler.js:58:19)
    at C:\Users\Alec\Code\react-server-test\node_modules\webpack\lib\Compiler.js:275:11```

**Comment by gestone** [comment]
Running into the same issue. Any fixes besides downgrading the version of node?

**Comment by hugotox** [comment]
Same issue. Mac 10.12.6, node 8.3.0

**Comment by dfadev** [comment]
See PR #947

**Comment by jdt1204** [comment]
It appears that this has been merged, though projects built with the Yeoman generator still have this issue. Any ETA on when the generator will be updated?

**Comment by gigabo** [comment]
I've updated the dependency versions in the generator in [`v0.7.1`](https://github.com/redfin/react-server/releases/tag/v0.7.1).

**Comment by dfadev** [comment]
`npm publish`?
