### ISSUE TITLE
react-server fails to start on fresh setup

### ISSUE THREAD

**Issue by anuragsn7** [redfin/react-server#971]
Hi, 

On OSX with node `v7.7.4`, fresh setup of react-server project fails to start.

```
$ react-server init
No package.json found.  Running `npm init --yes`
Wrote to /Users/myhome/Projects/sample/package.json:

{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Installing dependencies

$ react-server add-page '/' Homepage
Generating pages/Homepage.js
Updating routes.json
All set!

$ react-server start
{ Error: Cannot find module 'express-state'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myhome/.nvm/versions/node/v7.7.4/lib/node_modules/react-server-cli/target/commands/start.js:65:21)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/myhome/.nvm/versions/node/v7.7.4/lib/node_modules/react-server-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by gigabo** [comment]
Yikes, that's not good. Thanks for reporting @anuragsn7.
